package: community.lazycat.app.kaneo
version: 2.18.0
name: Kaneo
description: A focused, self-hosted project management platform for teams.
min_os_version: 1.5.0
author: usekaneo
license: MIT
homepage: https://github.com/usekaneo/kaneo
permissions:
  required:
    - net.internet
locales:
  zh:
    name: Kaneo
    description: 简洁高效的开源自托管项目管理平台。
  en:
    name: Kaneo
    description: A focused, self-hosted project management platform for teams.
